steps:
  - name: 'maven:3.9.1'
    args: ['package']
    entrypoint: mvn

  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'tool/target/datacommons-import-tool-0.1-jar-with-dependencies.jar', 'gs://datacommons_public/import_tools/import-tool.jar']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'triggers', 'run', 'dc-import-executor', '--branch=master', '--substitutions', '_DOCKER_IMAGE=us-docker.pkg.dev/datcom-ci/gcr.io/dc-import-executor']
