steps:
  - name: 'maven:3.9.1'
    args: ['package']
    entrypoint: mvn
    secretEnv:
      - AUTOPUSH_DC_API_KEY

  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Find the JAR file using wildcard
        JAR_FILE=$(ls tool/target/datacommons-import-tool-*-jar-with-dependencies.jar | head -n 1)
        echo "Found JAR: ${JAR_FILE}"
        gsutil cp "${JAR_FILE}" "gs://datacommons_public/import_tools/import-tool.jar"

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['builds', 'triggers', 'run', 'dc-import-executor', '--branch=master', '--substitutions', '_DOCKER_IMAGE=us-docker.pkg.dev/datcom-ci/gcr.io/dc-import-executor']

availableSecrets:
  secretManager:
    - versionName: projects/datcom-ci/secrets/autopush-dc-api-key/versions/latest
      env: AUTOPUSH_DC_API_KEY

