import os
import glob
import csv
import json
import argparse
from collections import defaultdict

def count_nodes(input_dir, pattern):
    count = 0
    search_path = os.path.join(input_dir, pattern)
    for filepath in glob.glob(search_path):
        # Exclude 'modified_previous' as it contains the old state of modified nodes
        if "modified_previous" in filepath:
            continue
        with open(filepath, 'r', encoding='utf-8') as f:
            for line in f:
                if line.strip().startswith('Node:'):
                    count += 1
    return count

def generate_report(input_dir, output_csv, output_json):
    # stats[var_measured] = {'ADDED': 0, 'DELETED': 0, 'MODIFIED': 0}
    stats = defaultdict(lambda: {'ADDED': 0, 'DELETED': 0, 'MODIFIED': 0})

    # Map file patterns for CSV generation
    file_patterns = {
        'ADDED': 'obs-added-*.mcf',
        'DELETED': 'obs-deleted-*.mcf',
        'MODIFIED': 'obs-modified-*.mcf'
    }

    for mutation_type, pattern in file_patterns.items():
        search_path = os.path.join(input_dir, pattern)
        for filepath in glob.glob(search_path):
            with open(filepath, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line.startswith('variableMeasured:'):
                        # Extract the value, e.g., "dcid:InterestRate_TreasuryBill_3Month"
                        parts = line.split(':', 1)
                        if len(parts) > 1:
                            var_measured = parts[1].strip()
                            # Strip quotes if accidentally quoted
                            var_measured = var_measured.strip('"\'')
                            stats[var_measured][mutation_type] += 1

    # Write to CSV
    with open(output_csv, 'w', newline='', encoding='utf-8') as f:
        writer = csv.writer(f)
        writer.writerow(['variableMeasured', 'ADDED', 'DELETED', 'MODIFIED'])
        for var_measured in sorted(stats.keys()):
            counts = stats[var_measured]
            writer.writerow([
                var_measured, 
                counts['ADDED'], 
                counts['DELETED'], 
                counts['MODIFIED']
            ])

    # Generate Summary JSON
    summary = {
        "added_obs_count": count_nodes(input_dir, 'obs-added-*.mcf'),
        "deleted_obs_count": count_nodes(input_dir, 'obs-deleted-*.mcf'),
        "modified_obs_count": count_nodes(input_dir, 'obs-modified-*.mcf'),
        "added_schema_count": count_nodes(input_dir, 'schema-added-*.mcf'),
        "deleted_schema_count": count_nodes(input_dir, 'schema-deleted-*.mcf'),
        "modified_schema_count": count_nodes(input_dir, 'schema-modified-*.mcf'),
    }

    # Load input counts from report.json generated by Dataflow
    report_json_path = os.path.join(input_dir, 'report.json')
    if os.path.exists(report_json_path):
        try:
            with open(report_json_path, 'r') as f:
                dataflow_report = json.load(f)
                summary["previous_obs_count"] = dataflow_report.get("previous_obs_count", 0)
                summary["current_obs_count"] = dataflow_report.get("current_obs_count", 0)
                summary["previous_schema_count"] = dataflow_report.get("previous_schema_count", 0)
                summary["current_schema_count"] = dataflow_report.get("current_schema_count", 0)
        except Exception as e:
            print(f"Warning: Could not read report.json: {e}")
    else:
         print(f"Warning: {report_json_path} not found. Input counts will be missing from summary.")

    # Write Summary JSON
    with open(output_json, 'w', encoding='utf-8') as f:
        json.dump(summary, f, indent=2)

    print(f"CSV report generated at {output_csv}")
    print(f"Summary JSON generated at {output_json}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Generate CSV and JSON reports from differ outputs.')
    parser.add_argument('--input_dir', required=True, help='Directory containing MCF files and report.json.')
    parser.add_argument('--output_csv', required=True, help='Path to the output CSV file.')
    parser.add_argument('--output_json', required=True, help='Path to the output summary JSON file.')
    args = parser.parse_args()
    generate_report(args.input_dir, args.output_csv, args.output_json)
