# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import functools
import re

import fs.path as fspath
from util.filesystem import File


def match(f: File, pattern: str) -> bool:
  """Returns true if this file's name or path matches a given pattern.

  Standard Glob Rules:
  - A leading double slash means the path must match from the absolute filesystem root.
  - A leading single slash will match the full path relative to the input dir.
  - '*' matches any characters within a single directory level.
  - '**' matches zero or more recursive directory levels.
  - '?' matches any single character (except a slash).
  - '{a,b}' matches alternative options (standard brace expansion).
  - '(a|b)' matches alternative options (standard parenthesis grouping).
  """
  original_pattern = pattern

  # 1. Parse pattern context
  protocol, pattern_body, anchored = _parse_pattern(pattern)

  # 2. Check protocol if specified (lazy evaluation)
  if protocol:
    if "://" not in f.full_path():
      return False
    file_protocol, _ = f.full_path().split("://", 1)
    protocol_regex = _glob_to_regex(protocol)
    if not _full_match(protocol_regex, file_protocol):
      return False

  # 3. Compile the entire pattern body to a single unified regex
  regex_str = _glob_to_regex_unified(pattern_body)

  # 4. Determine the target path for matching
  if anchored:
    if protocol:
      target = f.full_path().split("://", 1)[1]
    elif original_pattern.startswith("//"):
      if "://" in f.full_path() and f.syspath() is not None:
        target = fspath.relpath(f.syspath())
      else:
        target = fspath.relpath(f.full_path())
    else:
      target = "/" + f.path.lstrip("/")
  else:
    target = "/" + f.path.lstrip("/")

  # 5. Build final anchored regex
  if anchored:
    regex = f"^(?:{regex_str})$"
  else:
    # Suffix match: must either start at the beginning of the target or follow a slash (non-greedy)
    regex = f"^(?:.*?\\/)?(?:{regex_str})$"

  return re.search(regex, target) is not None


def _parse_pattern(pattern: str) -> tuple[str | None, str, bool]:
  """Parses a pattern into (protocol, body, anchored) tuple."""
  anchored = False
  protocol = None

  if "://" in pattern:
    protocol, pattern = pattern.split("://", 1)
    anchored = True
  elif pattern.startswith("//"):
    pattern = pattern[2:]
    anchored = True
  elif pattern.startswith("/"):
    # Keep the leading slash in the pattern body so it matches the target's leading slash
    anchored = True

  return protocol, pattern, anchored


@functools.lru_cache(maxsize=256)
def _expand_braces(pattern: str) -> str:
  """Expands standard glob braces: '{dirA,dirB}' -> '(?:dirA|dirB)'."""
  def repl(match):
    return "(?:" + match.group(1).replace(",", "|") + ")"
  while True:
    new_pattern = re.sub(r"\{([^}]+)\}", repl, pattern)
    if new_pattern == pattern:
      break
    pattern = new_pattern
  return pattern


@functools.lru_cache(maxsize=256)
def _glob_to_regex_unified(pattern: str) -> str:
  """Translates a standard glob pattern to a single unified regex."""
  # 1. Expand standard braces first
  pattern = _expand_braces(pattern)

  # 2. Validate that double wildcards do not appear in the filename portion
  name_part = pattern.rsplit("/", 1)[1] if "/" in pattern else pattern
  if "**" in name_part:
    raise ValueError(
        f"Adjacent double wildcards in the name portion of a pattern are not supported. Pattern: {pattern}"
    )

  # 3. Escape all regex special characters except '*', '|', '(', ')' and '?'
  # We do not escape '?' to preserve the '(?:' syntax generated by brace expansion.
  for char in ["\\", ".", "^", "$", "+", "[", "]", "{", "}"]:
    pattern = pattern.replace(char, "\\" + char)

  # 4. Protect double wildcards temporarily
  pattern = pattern.replace("**", "__DOUBLE_WILDCARD__")

  # 5. Process single wildcards segment-by-segment
  segments = pattern.split("/")
  for i, seg in enumerate(segments):
    if seg == "*":
      segments[i] = "[^/]+"
    elif "*" in seg:
      segments[i] = seg.replace("*", "[^/]*")

  pattern = "/".join(segments)

  # 6. Translate protected double wildcards
  pattern = pattern.replace("/__DOUBLE_WILDCARD__", "(?:/.*)?")
  pattern = pattern.replace("__DOUBLE_WILDCARD__/", "(?:.*/)?")
  pattern = pattern.replace("__DOUBLE_WILDCARD__", ".*")

  return pattern


@functools.lru_cache(maxsize=256)
def _glob_to_regex(pattern: str) -> str:
  """Simple name/protocol glob translator (for simple non-path segments)."""
  if "**" in pattern:
    raise ValueError(
        f"Adjacent double wildcards in the name or protocol portion of a pattern are not supported. Pattern: {pattern}"
    )
  for char in ["\\", ".", "^", "$", "+", "?", "(", ")", "[", "]", "{", "}"]:
    pattern = pattern.replace(char, "\\" + char)
  return pattern.replace("*", ".*")


def _full_match(regex: str, value: str) -> bool:
  return re.search(f"^(?:{regex})$", value) is not None
