- embedding_label: "base_text_embedding"
  model_name: "NodeEmbeddingModel"
  task_type: "RETRIEVAL_QUERY"
  node_types:
    - "StatisticalVariable"
    - "Topic"
  node_filter_type: "NLStatisticalVariable"
