calculations:
  - type: PLACE_AGGREGATION
    input_imports: CensusACS5YearSurvey
    place_aggregation:
      from_place_types: State
      to_place_types: Country
    round: 1
    output_import: CensusACS5YearSurvey_AggCountry

  - type: PLACE_AGGREGATION
    input_imports: CensusSAHIE
    place_aggregation:
      from_place_types: State
      to_place_types: Country
    round: 1
    output_import: CensusSAHIE_AggCountry

  - type: PLACE_AGGREGATION
    input_imports: CDCMortality
    place_aggregation:
      from_place_types: County
      to_place_types: State
    round: 1
    output_import: CDCMortality_AggState

  - type: PLACE_AGGREGATION
    input_imports: CDCMortality_AggState
    place_aggregation:
      from_place_types: State
      to_place_types: Country
    round: 2
    output_import: CDCMortality_AggState_AggCountry

  # - type: PLACE_AGGREGATION
  #   input_imports: FBIGovCrime
  #   place_aggregation:
  #     from_place_types: State
  #     to_place_types: Country
  #   round: 1
  #   output_import: FBIGovCrime_AggCountry

  - type: PLACE_AGGREGATION
    input_imports: DEA_ARCOS
    place_aggregation:
      from_place_types: County
      to_place_types: State
    round: 1
    output_import: DEA_ARCOS_AggState

  - type: PLACE_AGGREGATION
    input_imports: DEA_ARCOS_AggState
    place_aggregation:
      from_place_types: State
      to_place_types: Country
    round: 2
    output_import: DEA_ARCOS_AggState_AggCountry

  - type: PLACE_AGGREGATION
    input_imports: EPA_EJSCREEN
    place_aggregation:
      from_place_types: CensusBlockGroup
      to_place_types: CensusTract
    round: 1
    output_import: EPA_EJSCREEN_AggCensusTract

  - type: PLACE_AGGREGATION
    input_imports: EPA_EJSCREEN_AggCensusTract
    place_aggregation:
      from_place_types: CensusTract
      to_place_types: County
    round: 2
    output_import: EPA_EJSCREEN_AggCensusTract_AggCounty

  - type: PLACE_AGGREGATION
    input_imports: DeepSolar
    place_aggregation:
      from_place_types: CensusBlockGroup
      to_place_types: CensusTract
    round: 1
    output_import: DeepSolar_AggCensusTract

  - type: PLACE_AGGREGATION
    input_imports: DeepSolar_AggCensusTract
    place_aggregation:
      from_place_types: CensusTract
      to_place_types: County
    round: 2
    output_import: DeepSolar_AggCensusTract_AggCounty

  - type: PLACE_AGGREGATION
    input_imports: EPA_GHGRP
    place_aggregation:
      from_place_types: EpaReportingFacility
      to_place_types: County
    round: 1
    output_import: EPA_GHGRP_AggCounty

  - type: PLACE_AGGREGATION
    input_imports: EPA_GHGRP
    place_aggregation:
      from_place_types: EpaReportingFacility
      to_place_types: CensusZipCodeTabulationArea
    round: 1
    output_import: EPA_GHGRP_AggCensusZipCodeTabulationArea

  - type: PLACE_AGGREGATION
    input_imports: EPA_GHGRP_AggCounty
    place_aggregation:
      from_place_types: County
      to_place_types: State
    round: 2
    output_import: EPA_GHGRP_AggCounty_AggState

  - type: PLACE_AGGREGATION
    input_imports: RFF_USGridGeo_WeatherVariabilityForecast
    place_aggregation:
      from_place_types: GeoGridPlace_0.25Deg
      to_place_types: County
      allow_multiple_to_places: true
    round: 1
    output_import: RFF_USGridGeo_WeatherVariabilityForecast_AggCounty

  - type: PLACE_AGGREGATION
    input_imports: India_RBIStateDomesticProduct
    place_aggregation:
      from_place_types: State
      to_place_types: Country
      allow_multiple_to_places: true
    round: 1
    output_import: India_RBIStateDomesticProduct_AggCountry

  - type: PLACE_AGGREGATION
    input_imports: India_RBIStateDomesticProduct_StatVarAgg
    place_aggregation:
      from_place_types: State
      to_place_types: Country
      allow_multiple_to_places: true
    round: 1
    output_import: India_RBIStateDomesticProduct_StatVarAgg_AggCountry
