calculations:
  - name: "CensusACS5YearSurvey: State -> Country Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - CensusACS5YearSurvey
    place_aggregation:
      from_place_types: State
      to_place_types: Country
    stage: 1
    output_import: CensusACS5YearSurvey_AggCountry

  - name: "CensusSAHIE: State -> Country Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - CensusSAHIE
    place_aggregation:
      from_place_types: State
      to_place_types: Country
    stage: 1
    output_import: CensusSAHIE_AggCountry

  - name: "CDCMortality: County -> State Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - CDCMortality
    place_aggregation:
      from_place_types: County
      to_place_types: State
    stage: 1
    output_import: CDCMortality_AggState

  - name: "CDCMortality: State -> Country Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - CDCMortality_AggState
    place_aggregation:
      from_place_types: State
      to_place_types: Country
    stage: 2
    output_import: CDCMortality_AggState_AggCountry

  - name: "DEA_ARCOS: County -> State Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - DEA_ARCOS
    place_aggregation:
      from_place_types: County
      to_place_types: State
    stage: 1
    output_import: DEA_ARCOS_AggState

  - name: "DEA_ARCOS: State -> Country Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - DEA_ARCOS_AggState
    place_aggregation:
      from_place_types: State
      to_place_types: Country
    stage: 2
    output_import: DEA_ARCOS_AggState_AggCountry

  - name: "EPA_EJSCREEN: CensusBlockGroup -> CensusTract Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - EPA_EJSCREEN
    place_aggregation:
      from_place_types: CensusBlockGroup
      to_place_types: CensusTract
    stage: 1
    output_import: EPA_EJSCREEN_AggCensusTract

  - name: "EPA_EJSCREEN: CensusTract -> County Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - EPA_EJSCREEN_AggCensusTract
    place_aggregation:
      from_place_types: CensusTract
      to_place_types: County
    stage: 2
    output_import: EPA_EJSCREEN_AggCensusTract_AggCounty

  - name: "DeepSolar: CensusBlockGroup -> CensusTract Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - DeepSolar
    place_aggregation:
      from_place_types: CensusBlockGroup
      to_place_types: CensusTract
    stage: 1
    output_import: DeepSolar_AggCensusTract

  - name: "DeepSolar: CensusTract -> County Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - DeepSolar_AggCensusTract
    place_aggregation:
      from_place_types: CensusTract
      to_place_types: County
    stage: 2
    output_import: DeepSolar_AggCensusTract_AggCounty

  - name: "EPA_GHGRP: EpaReportingFacility -> County Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - EPA_GHGRP
    place_aggregation:
      from_place_types: EpaReportingFacility
      to_place_types: County
    stage: 1
    output_import: EPA_GHGRP_AggCounty

  - name: "EPA_GHGRP: EpaReportingFacility -> CensusZipCodeTabulationArea Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - EPA_GHGRP
    place_aggregation:
      from_place_types: EpaReportingFacility
      to_place_types: CensusZipCodeTabulationArea
    stage: 1
    output_import: EPA_GHGRP_AggCensusZipCodeTabulationArea

  - name: "EPA_GHGRP: County -> State Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - EPA_GHGRP_AggCounty
    place_aggregation:
      from_place_types: County
      to_place_types: State
    stage: 2
    output_import: EPA_GHGRP_AggCounty_AggState

  - name: "RFF_USGridGeo: GeoGrid -> County Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - RFF_USGridGeo_WeatherVariabilityForecast
    place_aggregation:
      from_place_types: GeoGridPlace_0.25Deg
      to_place_types: County
      allow_multiple_to_places: true
    stage: 1
    output_import: RFF_USGridGeo_WeatherVariabilityForecast_AggCounty

  - name: "India_RBIStateDomesticProduct: State -> Country Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - India_RBIStateDomesticProduct
    place_aggregation:
      from_place_types: State
      to_place_types: Country
      allow_multiple_to_places: true
    stage: 1
    output_import: India_RBIStateDomesticProduct_AggCountry

  - name: "India_RBIStateDomesticProduct: StatVarAgg State -> Country Place Rollup"
    type: PLACE_AGGREGATION
    input_imports:
      - India_RBIStateDomesticProduct_StatVarAgg
    place_aggregation:
      from_place_types: State
      to_place_types: Country
      allow_multiple_to_places: true
    stage: 1
    output_import: India_RBIStateDomesticProduct_StatVarAgg_AggCountry
