calculations:
  - name: "NASA_NEXDCP30: Measurement Methods & Base Date Diff Series Aggregation"
    type: STAT_VAR_SERIES_AGGREGATION
    input_imports:
      - NASA_NEXDCP30
    stage: 1
    output_import: NASA_NEXDCP30_AggrDiffStats
    stat_var_series_aggregation:
      aggr_funcs:
        - max_diff_across_measurement_methods: {}
        - diff_relative_to_base_date:
            date_specs:
              - dates:
                  - "1990"
                  - "2006"

  - name: "NASA_NEXGDDP_Subnational: Measurement Methods & Base Date Diff Series Aggregation"
    type: STAT_VAR_SERIES_AGGREGATION
    input_imports:
      - NASA_NEXGDDP_Subnational
    stage: 1
    output_import: NASA_NEXGDDP_Subnational_AggrDiffStats
    stat_var_series_aggregation:
      aggr_funcs:
        - max_diff_across_measurement_methods: {}
        - diff_relative_to_base_date:
            date_specs:
              - start_date: "2006"
                end_date: "2020"
              - dates:
                  - "1990"
                  - "2006"

  - name: "NASA_NEXGDDP_Country: Measurement Methods & Base Date Diff Series Aggregation"
    type: STAT_VAR_SERIES_AGGREGATION
    input_imports:
      - NASA_NEXGDDP_Country
    stage: 1
    output_import: NASA_NEXGDDP_Country_AggrDiffStats
    stat_var_series_aggregation:
      aggr_funcs:
        - max_diff_across_measurement_methods: {}
        - diff_relative_to_base_date:
            date_specs:
              - dates:
                  - "1990"
                  - "2006"

  - name: "NASA_NEXGDDP_CMIP6_Subnational: Measurement Methods & Base Date Diff Series Aggregation"
    type: STAT_VAR_SERIES_AGGREGATION
    input_imports:
      - NASA_NEXGDDP_CMIP6_Subnational
    stage: 1
    output_import: NASA_NEXGDDP_CMIP6_Subnational_AggrDiffStats
    stat_var_series_aggregation:
      aggr_funcs:
        - max_diff_across_measurement_methods: {}
        - diff_relative_to_base_date:
            date_specs:
              - start_date: "2015"
                end_date: "2020"
              - dates:
                  - "1990"
                  - "2006"

  - name: "NASA_NEXGDDP_CMIP6_IpccPlaces50: Measurement Methods & Base Date Diff Series Aggregation"
    type: STAT_VAR_SERIES_AGGREGATION
    input_imports:
      - NASA_NEXGDDP_CMIP6_IpccPlaces50
    stage: 1
    output_import: NASA_NEXGDDP_CMIP6_IpccPlaces50_AggrDiffStats
    stat_var_series_aggregation:
      aggr_funcs:
        - max_diff_across_measurement_methods: {}
        - diff_relative_to_base_date:
            date_specs:
              - start_date: "2015"
                end_date: "2020"
              - dates:
                  - "1990"
                  - "2006"

  - name: "NASA_NEXGDDP_CMIP6_Subnational: Stats Across Models Series Aggregation"
    type: STAT_VAR_SERIES_AGGREGATION
    input_imports:
      - NASA_NEXGDDP_CMIP6_Subnational
    stage: 2
    output_import: NASA_NEXGDDP_CMIP6_Subnational_AggrStatsAcrossModels
    stat_var_series_aggregation:
      aggr_funcs:
        - aggr_stats_across_models:
            sv_regex: "^DifferenceRelativeToObservationalData_.*"
            aggregation_ops:
              - OPERATOR_MEDIAN
              - OPERATOR_PERCENTILE90
              - OPERATOR_PERCENTILE10

  - name: "NASA_NEXGDDP_CMIP6_IpccPlaces50: Stats Across Models Series Aggregation"
    type: STAT_VAR_SERIES_AGGREGATION
    input_imports:
      - NASA_NEXGDDP_CMIP6_IpccPlaces50
    stage: 2
    output_import: NASA_NEXGDDP_CMIP6_IpccPlaces50_AggrStatsAcrossModels
    stat_var_series_aggregation:
      aggr_funcs:
        - aggr_stats_across_models:
            sv_regex: "^DifferenceRelativeToObservationalData_.*"
            aggregation_ops:
              - OPERATOR_MEDIAN
              - OPERATOR_PERCENTILE90
              - OPERATOR_PERCENTILE10

  - name: "NASA_NEXGDDP_CMIP6_Subnational: Over Time Stats Across Models Series Aggregation"
    type: STAT_VAR_SERIES_AGGREGATION
    input_imports:
      - NASA_NEXGDDP_CMIP6_Subnational_AggrStatsAcrossModels
    stage: 3
    output_import: NASA_NEXGDDP_CMIP6_Subnational_AggrOverTimeOnStatsAcrossModels
    stat_var_series_aggregation:
      aggr_funcs:
        # Config for future 10-year max/min aggregate
        - aggr_over_time:
            time_range:
              input_obs_period: P1M
              output_obs_period: P10Y
              output_obs_date: "2030"
            sv_configs:
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Max_Temperature.*"
                aggregation_op: OPERATOR_MAX
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Min_Temperature.*"
                aggregation_op: OPERATOR_MIN
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate((?!Max|Min).)*_Temperature.*"
                aggregation_op: OPERATOR_MEAN

        # Config for future 30-year max/min aggregate
        - aggr_over_time:
            time_range:
              input_obs_period: P1M
              output_obs_period: P30Y
              output_obs_date: "2050"
            sv_configs:
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Max_Temperature.*"
                aggregation_op: OPERATOR_MAX
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Min_Temperature.*"
                aggregation_op: OPERATOR_MIN
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate((?!Max|Min).)*_Temperature.*"
                aggregation_op: OPERATOR_MEAN

        # Config for future 80-year max/min aggregate
        - aggr_over_time:
            time_range:
              input_obs_period: P1M
              output_obs_period: P80Y
              output_obs_date: "2100"
            sv_configs:
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Max_Temperature.*"
                aggregation_op: OPERATOR_MAX
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Min_Temperature.*"
                aggregation_op: OPERATOR_MIN
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate((?!Max|Min).)*_Temperature.*"
                aggregation_op: OPERATOR_MEAN

        # Config for future 10-year period of num-months with max/min temp above/below threshold
        - count_threshold_exception_over_time:
            time_range:
              input_obs_period: P1M
              output_obs_period: P10Y
              output_obs_date: "2030"
            thresholds:
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Max_Temperature.*"
                threshold_value: 5
                unit: Celsius
                comparison: OPERATOR_GE
                output_cprop: maxTemperature
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Min_Temperature.*"
                threshold_value: -5
                unit: Celsius
                comparison: OPERATOR_LE
                output_cprop: minTemperature

        # Config for future 30-year period of num-months with max/min temp above/below threshold
        - count_threshold_exception_over_time:
            time_range:
              input_obs_period: P1M
              output_obs_period: P30Y
              output_obs_date: "2050"
            thresholds:
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Max_Temperature.*"
                threshold_value: 5
                unit: Celsius
                comparison: OPERATOR_GE
                output_cprop: maxTemperature
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Min_Temperature.*"
                threshold_value: -5
                unit: Celsius
                comparison: OPERATOR_LE
                output_cprop: minTemperature

        # Config for future 80-year period of num-months with max/min temp above/below threshold
        - count_threshold_exception_over_time:
            time_range:
              input_obs_period: P1M
              output_obs_period: P80Y
              output_obs_date: "2100"
            thresholds:
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Max_Temperature.*"
                threshold_value: 5
                unit: Celsius
                comparison: OPERATOR_GE
                output_cprop: maxTemperature
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Min_Temperature.*"
                threshold_value: -5
                unit: Celsius
                comparison: OPERATOR_LE
                output_cprop: minTemperature

  - name: "NASA_NEXGDDP_CMIP6_IpccPlaces50: Over Time Stats Across Models Series Aggregation"
    type: STAT_VAR_SERIES_AGGREGATION
    input_imports:
      - NASA_NEXGDDP_CMIP6_IpccPlaces50_AggrStatsAcrossModels
    stage: 3
    output_import: NASA_NEXGDDP_CMIP6_IpccPlaces50_AggrOverTimeOnStatsAcrossModels
    stat_var_series_aggregation:
      aggr_funcs:
        # Config for future 10-year max/min aggregate
        - aggr_over_time:
            time_range:
              input_obs_period: P1M
              output_obs_period: P10Y
              output_obs_date: "2030"
            sv_configs:
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Max_Temperature.*"
                aggregation_op: OPERATOR_MAX
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Min_Temperature.*"
                aggregation_op: OPERATOR_MIN
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate((?!Max|Min).)*_Temperature.*"
                aggregation_op: OPERATOR_MEAN

        # Config for future 30-year max/min aggregate
        - aggr_over_time:
            time_range:
              input_obs_period: P1M
              output_obs_period: P30Y
              output_obs_date: "2050"
            sv_configs:
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Max_Temperature.*"
                aggregation_op: OPERATOR_MAX
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Min_Temperature.*"
                aggregation_op: OPERATOR_MIN
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate((?!Max|Min).)*_Temperature.*"
                aggregation_op: OPERATOR_MEAN

        # Config for future 80-year max/min aggregate
        - aggr_over_time:
            time_range:
              input_obs_period: P1M
              output_obs_period: P80Y
              output_obs_date: "2100"
            sv_configs:
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Max_Temperature.*"
                aggregation_op: OPERATOR_MAX
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Min_Temperature.*"
                aggregation_op: OPERATOR_MIN
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate((?!Max|Min).)*_Temperature.*"
                aggregation_op: OPERATOR_MEAN

        # Config for future 10-year period of num-months with max/min temp above/below threshold
        - count_threshold_exception_over_time:
            time_range:
              input_obs_period: P1M
              output_obs_period: P10Y
              output_obs_date: "2030"
            thresholds:
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Max_Temperature.*"
                threshold_value: 5
                unit: Celsius
                comparison: OPERATOR_GE
                output_cprop: maxTemperature
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Min_Temperature.*"
                threshold_value: -5
                unit: Celsius
                comparison: OPERATOR_LE
                output_cprop: minTemperature

        # Config for future 30-year period of num-months with max/min temp above/below threshold
        - count_threshold_exception_over_time:
            time_range:
              input_obs_period: P1M
              output_obs_period: P30Y
              output_obs_date: "2050"
            thresholds:
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Max_Temperature.*"
                threshold_value: 5
                unit: Celsius
                comparison: OPERATOR_GE
                output_cprop: maxTemperature
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Min_Temperature.*"
                threshold_value: -5
                unit: Celsius
                comparison: OPERATOR_LE
                output_cprop: minTemperature

        # Config for future 80-year period of num-months with max/min temp above/below threshold
        - count_threshold_exception_over_time:
            time_range:
              input_obs_period: P1M
              output_obs_period: P80Y
              output_obs_date: "2100"
            thresholds:
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Max_Temperature.*"
                threshold_value: 5
                unit: Celsius
                comparison: OPERATOR_GE
                output_cprop: maxTemperature
              - sv_regex: "^(Median|Percentile90|Percentile10)AcrossModels_DifferenceRelativeToBaseDate.*_Min_Temperature.*"
                threshold_value: -5
                unit: Celsius
                comparison: OPERATOR_LE
                output_cprop: minTemperature

  - name: "NASA_NEXGDDP_IpccPlaces50: Measurement Methods & Base Date Diff Series Aggregation"
    type: STAT_VAR_SERIES_AGGREGATION
    input_imports:
      - NASA_NEXGDDP_IpccPlaces50
    stage: 1
    output_import: NASA_NEXGDDP_IpccPlaces50_AggrDiffStats
    stat_var_series_aggregation:
      aggr_funcs:
        - max_diff_across_measurement_methods: {}
        - diff_relative_to_base_date:
            date_specs:
              - start_date: "2015"
                end_date: "2020"
              - dates:
                  - "1990"
                  - "2006"
