#  gcloud builds submit --config pipeline/ingestion/cloudbuild.yaml .

steps:
  # 1. Build the bundled JAR using Maven
  # We run from the root to ensure all modules (model, util, ingestion) are built correctly.
  - name: 'maven:3.9-eclipse-temurin-17'
    entrypoint: 'mvn'
    args:
      - 'clean'
      - 'package'
      - '-Pdataflow-runner'
      - '-pl'
      - 'pipeline/ingestion'
      - '-am'
    secretEnv:
      - AUTOPUSH_DC_API_KEY
    id: 'build-jar'

  # 2. Build the Dataflow Flex Template
  # This step uses the built JAR to create the Flex Template image and spec file.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Find the JAR file using wildcard
        # Note: We are in the root of the workspace context for the build.
        JAR_FILE=$(ls pipeline/ingestion/target/ingestion-bundled-*.jar | head -n 1)
        echo "Found JAR: ${JAR_FILE}"

        gcloud dataflow flex-template build \
          gs://$_TEMPLATE_BUCKET/templates/flex/ingestion.json \
          --image-gcr-path "${_IMAGE_GCR_PATH}:$SHORT_SHA" \
          --sdk-language JAVA \
          --flex-template-base-image JAVA17 \
          --metadata-file pipeline/ingestion/metadata.json \
          --jar "${JAR_FILE}" \
          --env FLEX_TEMPLATE_JAVA_MAIN_CLASS=org.datacommons.ingestion.pipeline.ImportGroupPipeline
    id: 'build-flex-template'

availableSecrets:
  secretManager:
    - versionName: projects/datcom-ci/secrets/autopush-dc-api-key/versions/latest
      env: AUTOPUSH_DC_API_KEY

substitutions:

  _TEMPLATE_BUCKET: "datcom-templates"
  _IMAGE_GCR_PATH: "gcr.io/datcom-ci/dataflow-templates/ingestion"
