// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ErrorCounters.proto

package org.datacommons.proto;

public final class ErrorCountersOuterClass {
  private ErrorCountersOuterClass() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public interface ErrorCountersOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:org.datacommons.proto.ErrorCounters)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
     */
    java.util.List<org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter>
        getErrorCountersList();
    /**
     * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
     */
    org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter getErrorCounters(
        int index);
    /**
     * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
     */
    int getErrorCountersCount();
    /**
     * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
     */
    java.util.List<
            ? extends
                org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounterOrBuilder>
        getErrorCountersOrBuilderList();
    /**
     * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
     */
    org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounterOrBuilder
        getErrorCountersOrBuilder(int index);
  }
  /**
   *
   *
   * <pre>
   * A log of import processing with details on any warnings, errors, etc.
   * </pre>
   *
   * Protobuf type {@code org.datacommons.proto.ErrorCounters}
   */
  public static final class ErrorCounters extends com.google.protobuf.GeneratedMessageV3
      implements
      // @@protoc_insertion_point(message_implements:org.datacommons.proto.ErrorCounters)
      ErrorCountersOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use ErrorCounters.newBuilder() to construct.
    private ErrorCounters(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }

    private ErrorCounters() {
      errorCounters_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
      return new ErrorCounters();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
      return this.unknownFields;
    }

    private ErrorCounters(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10:
              {
                if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                  errorCounters_ =
                      new java.util.ArrayList<
                          org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters
                              .ErrorCounter>();
                  mutable_bitField0_ |= 0x00000001;
                }
                errorCounters_.add(
                    input.readMessage(
                        org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
                            .PARSER,
                        extensionRegistry));
                break;
              }
            default:
              {
                if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          errorCounters_ = java.util.Collections.unmodifiableList(errorCounters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
      return org.datacommons.proto.ErrorCountersOuterClass
          .internal_static_org_datacommons_proto_ErrorCounters_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.datacommons.proto.ErrorCountersOuterClass
          .internal_static_org_datacommons_proto_ErrorCounters_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.class,
              org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.Builder.class);
    }

    public interface ErrorCounterOrBuilder
        extends
        // @@protoc_insertion_point(interface_extends:org.datacommons.proto.ErrorCounters.ErrorCounter)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional string counter_name = 1;</code>
       *
       * @return Whether the counterName field is set.
       */
      boolean hasCounterName();
      /**
       * <code>optional string counter_name = 1;</code>
       *
       * @return The counterName.
       */
      java.lang.String getCounterName();
      /**
       * <code>optional string counter_name = 1;</code>
       *
       * @return The bytes for counterName.
       */
      com.google.protobuf.ByteString getCounterNameBytes();

      /**
       * <code>optional bool is_prefix = 2;</code>
       *
       * @return Whether the isPrefix field is set.
       */
      boolean hasIsPrefix();
      /**
       * <code>optional bool is_prefix = 2;</code>
       *
       * @return The isPrefix.
       */
      boolean getIsPrefix();

      /**
       *
       *
       * <pre>
       * imported from Debug.proto
       * </pre>
       *
       * <code>optional .org.datacommons.proto.Log.Level level = 3;</code>
       *
       * @return Whether the level field is set.
       */
      boolean hasLevel();
      /**
       *
       *
       * <pre>
       * imported from Debug.proto
       * </pre>
       *
       * <code>optional .org.datacommons.proto.Log.Level level = 3;</code>
       *
       * @return The level.
       */
      org.datacommons.proto.Debug.Log.Level getLevel();

      /**
       * <code>repeated string user_actions = 4;</code>
       *
       * @return A list containing the userActions.
       */
      java.util.List<java.lang.String> getUserActionsList();
      /**
       * <code>repeated string user_actions = 4;</code>
       *
       * @return The count of userActions.
       */
      int getUserActionsCount();
      /**
       * <code>repeated string user_actions = 4;</code>
       *
       * @param index The index of the element to return.
       * @return The userActions at the given index.
       */
      java.lang.String getUserActions(int index);
      /**
       * <code>repeated string user_actions = 4;</code>
       *
       * @param index The index of the value to return.
       * @return The bytes of the userActions at the given index.
       */
      com.google.protobuf.ByteString getUserActionsBytes(int index);
    }
    /** Protobuf type {@code org.datacommons.proto.ErrorCounters.ErrorCounter} */
    public static final class ErrorCounter extends com.google.protobuf.GeneratedMessageV3
        implements
        // @@protoc_insertion_point(message_implements:org.datacommons.proto.ErrorCounters.ErrorCounter)
        ErrorCounterOrBuilder {
      private static final long serialVersionUID = 0L;
      // Use ErrorCounter.newBuilder() to construct.
      private ErrorCounter(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }

      private ErrorCounter() {
        counterName_ = "";
        level_ = 0;
        userActions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(UnusedPrivateParameter unused) {
        return new ErrorCounter();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return this.unknownFields;
      }

      private ErrorCounter(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10:
                {
                  com.google.protobuf.ByteString bs = input.readBytes();
                  bitField0_ |= 0x00000001;
                  counterName_ = bs;
                  break;
                }
              case 16:
                {
                  bitField0_ |= 0x00000002;
                  isPrefix_ = input.readBool();
                  break;
                }
              case 24:
                {
                  int rawValue = input.readEnum();
                  @SuppressWarnings("deprecation")
                  org.datacommons.proto.Debug.Log.Level value =
                      org.datacommons.proto.Debug.Log.Level.valueOf(rawValue);
                  if (value == null) {
                    unknownFields.mergeVarintField(3, rawValue);
                  } else {
                    bitField0_ |= 0x00000004;
                    level_ = rawValue;
                  }
                  break;
                }
              case 34:
                {
                  com.google.protobuf.ByteString bs = input.readBytes();
                  if (!((mutable_bitField0_ & 0x00000008) != 0)) {
                    userActions_ = new com.google.protobuf.LazyStringArrayList();
                    mutable_bitField0_ |= 0x00000008;
                  }
                  userActions_.add(bs);
                  break;
                }
              default:
                {
                  if (!parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                    done = true;
                  }
                  break;
                }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(this);
        } finally {
          if (((mutable_bitField0_ & 0x00000008) != 0)) {
            userActions_ = userActions_.getUnmodifiableView();
          }
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }

      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return org.datacommons.proto.ErrorCountersOuterClass
            .internal_static_org_datacommons_proto_ErrorCounters_ErrorCounter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.datacommons.proto.ErrorCountersOuterClass
            .internal_static_org_datacommons_proto_ErrorCounters_ErrorCounter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.class,
                org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.Builder
                    .class);
      }

      private int bitField0_;
      public static final int COUNTER_NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object counterName_;
      /**
       * <code>optional string counter_name = 1;</code>
       *
       * @return Whether the counterName field is set.
       */
      public boolean hasCounterName() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string counter_name = 1;</code>
       *
       * @return The counterName.
       */
      public java.lang.String getCounterName() {
        java.lang.Object ref = counterName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            counterName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string counter_name = 1;</code>
       *
       * @return The bytes for counterName.
       */
      public com.google.protobuf.ByteString getCounterNameBytes() {
        java.lang.Object ref = counterName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
          counterName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int IS_PREFIX_FIELD_NUMBER = 2;
      private boolean isPrefix_;
      /**
       * <code>optional bool is_prefix = 2;</code>
       *
       * @return Whether the isPrefix field is set.
       */
      public boolean hasIsPrefix() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional bool is_prefix = 2;</code>
       *
       * @return The isPrefix.
       */
      public boolean getIsPrefix() {
        return isPrefix_;
      }

      public static final int LEVEL_FIELD_NUMBER = 3;
      private int level_;
      /**
       *
       *
       * <pre>
       * imported from Debug.proto
       * </pre>
       *
       * <code>optional .org.datacommons.proto.Log.Level level = 3;</code>
       *
       * @return Whether the level field is set.
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       *
       *
       * <pre>
       * imported from Debug.proto
       * </pre>
       *
       * <code>optional .org.datacommons.proto.Log.Level level = 3;</code>
       *
       * @return The level.
       */
      public org.datacommons.proto.Debug.Log.Level getLevel() {
        @SuppressWarnings("deprecation")
        org.datacommons.proto.Debug.Log.Level result =
            org.datacommons.proto.Debug.Log.Level.valueOf(level_);
        return result == null ? org.datacommons.proto.Debug.Log.Level.LEVEL_UNSPECIFIED : result;
      }

      public static final int USER_ACTIONS_FIELD_NUMBER = 4;
      private com.google.protobuf.LazyStringList userActions_;
      /**
       * <code>repeated string user_actions = 4;</code>
       *
       * @return A list containing the userActions.
       */
      public com.google.protobuf.ProtocolStringList getUserActionsList() {
        return userActions_;
      }
      /**
       * <code>repeated string user_actions = 4;</code>
       *
       * @return The count of userActions.
       */
      public int getUserActionsCount() {
        return userActions_.size();
      }
      /**
       * <code>repeated string user_actions = 4;</code>
       *
       * @param index The index of the element to return.
       * @return The userActions at the given index.
       */
      public java.lang.String getUserActions(int index) {
        return userActions_.get(index);
      }
      /**
       * <code>repeated string user_actions = 4;</code>
       *
       * @param index The index of the value to return.
       * @return The bytes of the userActions at the given index.
       */
      public com.google.protobuf.ByteString getUserActionsBytes(int index) {
        return userActions_.getByteString(index);
      }

      private byte memoizedIsInitialized = -1;

      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, counterName_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeBool(2, isPrefix_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          output.writeEnum(3, level_);
        }
        for (int i = 0; i < userActions_.size(); i++) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userActions_.getRaw(i));
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, counterName_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream.computeBoolSize(2, isPrefix_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.CodedOutputStream.computeEnumSize(3, level_);
        }
        {
          int dataSize = 0;
          for (int i = 0; i < userActions_.size(); i++) {
            dataSize += computeStringSizeNoTag(userActions_.getRaw(i));
          }
          size += dataSize;
          size += 1 * getUserActionsList().size();
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
          return true;
        }
        if (!(obj
            instanceof org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter)) {
          return super.equals(obj);
        }
        org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter other =
            (org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter) obj;

        if (hasCounterName() != other.hasCounterName()) return false;
        if (hasCounterName()) {
          if (!getCounterName().equals(other.getCounterName())) return false;
        }
        if (hasIsPrefix() != other.hasIsPrefix()) return false;
        if (hasIsPrefix()) {
          if (getIsPrefix() != other.getIsPrefix()) return false;
        }
        if (hasLevel() != other.hasLevel()) return false;
        if (hasLevel()) {
          if (level_ != other.level_) return false;
        }
        if (!getUserActionsList().equals(other.getUserActionsList())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasCounterName()) {
          hash = (37 * hash) + COUNTER_NAME_FIELD_NUMBER;
          hash = (53 * hash) + getCounterName().hashCode();
        }
        if (hasIsPrefix()) {
          hash = (37 * hash) + IS_PREFIX_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getIsPrefix());
        }
        if (hasLevel()) {
          hash = (37 * hash) + LEVEL_FIELD_NUMBER;
          hash = (53 * hash) + level_;
        }
        if (getUserActionsCount() > 0) {
          hash = (37 * hash) + USER_ACTIONS_FIELD_NUMBER;
          hash = (53 * hash) + getUserActionsList().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          parseFrom(java.nio.ByteBuffer data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          parseFrom(
              java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          parseFrom(com.google.protobuf.ByteString data)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          parseFrom(
              com.google.protobuf.ByteString data,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          parseFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          parseFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
            PARSER, input, extensionRegistry);
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          parseDelimitedFrom(
              java.io.InputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
            PARSER, input, extensionRegistry);
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          parseFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
            PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() {
        return newBuilder();
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }

      public static Builder newBuilder(
          org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /** Protobuf type {@code org.datacommons.proto.ErrorCounters.ErrorCounter} */
      public static final class Builder
          extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
          implements
          // @@protoc_insertion_point(builder_implements:org.datacommons.proto.ErrorCounters.ErrorCounter)
          org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounterOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
          return org.datacommons.proto.ErrorCountersOuterClass
              .internal_static_org_datacommons_proto_ErrorCounters_ErrorCounter_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.datacommons.proto.ErrorCountersOuterClass
              .internal_static_org_datacommons_proto_ErrorCounters_ErrorCounter_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.class,
                  org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.Builder
                      .class);
        }

        // Construct using
        // org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {}
        }

        @java.lang.Override
        public Builder clear() {
          super.clear();
          counterName_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          isPrefix_ = false;
          bitField0_ = (bitField0_ & ~0x00000002);
          level_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          userActions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
          return org.datacommons.proto.ErrorCountersOuterClass
              .internal_static_org_datacommons_proto_ErrorCounters_ErrorCounter_descriptor;
        }

        @java.lang.Override
        public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
            getDefaultInstanceForType() {
          return org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
              .getDefaultInstance();
        }

        @java.lang.Override
        public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter build() {
          org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter result =
              buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
            buildPartial() {
          org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter result =
              new org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            to_bitField0_ |= 0x00000001;
          }
          result.counterName_ = counterName_;
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.isPrefix_ = isPrefix_;
            to_bitField0_ |= 0x00000002;
          }
          if (((from_bitField0_ & 0x00000004) != 0)) {
            to_bitField0_ |= 0x00000004;
          }
          result.level_ = level_;
          if (((bitField0_ & 0x00000008) != 0)) {
            userActions_ = userActions_.getUnmodifiableView();
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.userActions_ = userActions_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }

        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
          return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index,
            java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other
              instanceof org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter) {
            return mergeFrom(
                (org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter) other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(
            org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter other) {
          if (other
              == org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
                  .getDefaultInstance()) return this;
          if (other.hasCounterName()) {
            bitField0_ |= 0x00000001;
            counterName_ = other.counterName_;
            onChanged();
          }
          if (other.hasIsPrefix()) {
            setIsPrefix(other.getIsPrefix());
          }
          if (other.hasLevel()) {
            setLevel(other.getLevel());
          }
          if (!other.userActions_.isEmpty()) {
            if (userActions_.isEmpty()) {
              userActions_ = other.userActions_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureUserActionsIsMutable();
              userActions_.addAll(other.userActions_);
            }
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter parsedMessage =
              null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage =
                (org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter)
                    e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int bitField0_;

        private java.lang.Object counterName_ = "";
        /**
         * <code>optional string counter_name = 1;</code>
         *
         * @return Whether the counterName field is set.
         */
        public boolean hasCounterName() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional string counter_name = 1;</code>
         *
         * @return The counterName.
         */
        public java.lang.String getCounterName() {
          java.lang.Object ref = counterName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              counterName_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string counter_name = 1;</code>
         *
         * @return The bytes for counterName.
         */
        public com.google.protobuf.ByteString getCounterNameBytes() {
          java.lang.Object ref = counterName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            counterName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string counter_name = 1;</code>
         *
         * @param value The counterName to set.
         * @return This builder for chaining.
         */
        public Builder setCounterName(java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          counterName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string counter_name = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearCounterName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          counterName_ = getDefaultInstance().getCounterName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string counter_name = 1;</code>
         *
         * @param value The bytes for counterName to set.
         * @return This builder for chaining.
         */
        public Builder setCounterNameBytes(com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          counterName_ = value;
          onChanged();
          return this;
        }

        private boolean isPrefix_;
        /**
         * <code>optional bool is_prefix = 2;</code>
         *
         * @return Whether the isPrefix field is set.
         */
        public boolean hasIsPrefix() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional bool is_prefix = 2;</code>
         *
         * @return The isPrefix.
         */
        public boolean getIsPrefix() {
          return isPrefix_;
        }
        /**
         * <code>optional bool is_prefix = 2;</code>
         *
         * @param value The isPrefix to set.
         * @return This builder for chaining.
         */
        public Builder setIsPrefix(boolean value) {
          bitField0_ |= 0x00000002;
          isPrefix_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bool is_prefix = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearIsPrefix() {
          bitField0_ = (bitField0_ & ~0x00000002);
          isPrefix_ = false;
          onChanged();
          return this;
        }

        private int level_ = 0;
        /**
         *
         *
         * <pre>
         * imported from Debug.proto
         * </pre>
         *
         * <code>optional .org.datacommons.proto.Log.Level level = 3;</code>
         *
         * @return Whether the level field is set.
         */
        public boolean hasLevel() {
          return ((bitField0_ & 0x00000004) != 0);
        }
        /**
         *
         *
         * <pre>
         * imported from Debug.proto
         * </pre>
         *
         * <code>optional .org.datacommons.proto.Log.Level level = 3;</code>
         *
         * @return The level.
         */
        public org.datacommons.proto.Debug.Log.Level getLevel() {
          @SuppressWarnings("deprecation")
          org.datacommons.proto.Debug.Log.Level result =
              org.datacommons.proto.Debug.Log.Level.valueOf(level_);
          return result == null ? org.datacommons.proto.Debug.Log.Level.LEVEL_UNSPECIFIED : result;
        }
        /**
         *
         *
         * <pre>
         * imported from Debug.proto
         * </pre>
         *
         * <code>optional .org.datacommons.proto.Log.Level level = 3;</code>
         *
         * @param value The level to set.
         * @return This builder for chaining.
         */
        public Builder setLevel(org.datacommons.proto.Debug.Log.Level value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000004;
          level_ = value.getNumber();
          onChanged();
          return this;
        }
        /**
         *
         *
         * <pre>
         * imported from Debug.proto
         * </pre>
         *
         * <code>optional .org.datacommons.proto.Log.Level level = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearLevel() {
          bitField0_ = (bitField0_ & ~0x00000004);
          level_ = 0;
          onChanged();
          return this;
        }

        private com.google.protobuf.LazyStringList userActions_ =
            com.google.protobuf.LazyStringArrayList.EMPTY;

        private void ensureUserActionsIsMutable() {
          if (!((bitField0_ & 0x00000008) != 0)) {
            userActions_ = new com.google.protobuf.LazyStringArrayList(userActions_);
            bitField0_ |= 0x00000008;
          }
        }
        /**
         * <code>repeated string user_actions = 4;</code>
         *
         * @return A list containing the userActions.
         */
        public com.google.protobuf.ProtocolStringList getUserActionsList() {
          return userActions_.getUnmodifiableView();
        }
        /**
         * <code>repeated string user_actions = 4;</code>
         *
         * @return The count of userActions.
         */
        public int getUserActionsCount() {
          return userActions_.size();
        }
        /**
         * <code>repeated string user_actions = 4;</code>
         *
         * @param index The index of the element to return.
         * @return The userActions at the given index.
         */
        public java.lang.String getUserActions(int index) {
          return userActions_.get(index);
        }
        /**
         * <code>repeated string user_actions = 4;</code>
         *
         * @param index The index of the value to return.
         * @return The bytes of the userActions at the given index.
         */
        public com.google.protobuf.ByteString getUserActionsBytes(int index) {
          return userActions_.getByteString(index);
        }
        /**
         * <code>repeated string user_actions = 4;</code>
         *
         * @param index The index to set the value at.
         * @param value The userActions to set.
         * @return This builder for chaining.
         */
        public Builder setUserActions(int index, java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserActionsIsMutable();
          userActions_.set(index, value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string user_actions = 4;</code>
         *
         * @param value The userActions to add.
         * @return This builder for chaining.
         */
        public Builder addUserActions(java.lang.String value) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserActionsIsMutable();
          userActions_.add(value);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string user_actions = 4;</code>
         *
         * @param values The userActions to add.
         * @return This builder for chaining.
         */
        public Builder addAllUserActions(java.lang.Iterable<java.lang.String> values) {
          ensureUserActionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(values, userActions_);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string user_actions = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearUserActions() {
          userActions_ = com.google.protobuf.LazyStringArrayList.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
          return this;
        }
        /**
         * <code>repeated string user_actions = 4;</code>
         *
         * @param value The bytes of the userActions to add.
         * @return This builder for chaining.
         */
        public Builder addUserActionsBytes(com.google.protobuf.ByteString value) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserActionsIsMutable();
          userActions_.add(value);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }

        // @@protoc_insertion_point(builder_scope:org.datacommons.proto.ErrorCounters.ErrorCounter)
      }

      // @@protoc_insertion_point(class_scope:org.datacommons.proto.ErrorCounters.ErrorCounter)
      private static final org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          DEFAULT_INSTANCE;

      static {
        DEFAULT_INSTANCE =
            new org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter();
      }

      public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      @java.lang.Deprecated
      public static final com.google.protobuf.Parser<ErrorCounter> PARSER =
          new com.google.protobuf.AbstractParser<ErrorCounter>() {
            @java.lang.Override
            public ErrorCounter parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
              return new ErrorCounter(input, extensionRegistry);
            }
          };

      public static com.google.protobuf.Parser<ErrorCounter> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<ErrorCounter> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }
    }

    public static final int ERROR_COUNTERS_FIELD_NUMBER = 1;
    private java.util.List<org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter>
        errorCounters_;
    /**
     * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
     */
    public java.util.List<org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter>
        getErrorCountersList() {
      return errorCounters_;
    }
    /**
     * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
     */
    public java.util.List<
            ? extends
                org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounterOrBuilder>
        getErrorCountersOrBuilderList() {
      return errorCounters_;
    }
    /**
     * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
     */
    public int getErrorCountersCount() {
      return errorCounters_.size();
    }
    /**
     * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
     */
    public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
        getErrorCounters(int index) {
      return errorCounters_.get(index);
    }
    /**
     * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
     */
    public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounterOrBuilder
        getErrorCountersOrBuilder(int index) {
      return errorCounters_.get(index);
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
      for (int i = 0; i < errorCounters_.size(); i++) {
        output.writeMessage(1, errorCounters_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < errorCounters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream.computeMessageSize(1, errorCounters_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters)) {
        return super.equals(obj);
      }
      org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters other =
          (org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters) obj;

      if (!getErrorCountersList().equals(other.getErrorCountersList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getErrorCountersCount() > 0) {
        hash = (37 * hash) + ERROR_COUNTERS_FIELD_NUMBER;
        hash = (53 * hash) + getErrorCountersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parseFrom(
        java.nio.ByteBuffer data) throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parseFrom(
        java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parseFrom(
        byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parseFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parseFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parseDelimitedFrom(
        java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parseDelimitedFrom(
        java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(
          PARSER, input, extensionRegistry);
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parseFrom(
        com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3.parseWithIOException(
          PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
      return newBuilder();
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(
        org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     *
     *
     * <pre>
     * A log of import processing with details on any warnings, errors, etc.
     * </pre>
     *
     * Protobuf type {@code org.datacommons.proto.ErrorCounters}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageV3.Builder<Builder>
        implements
        // @@protoc_insertion_point(builder_implements:org.datacommons.proto.ErrorCounters)
        org.datacommons.proto.ErrorCountersOuterClass.ErrorCountersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return org.datacommons.proto.ErrorCountersOuterClass
            .internal_static_org_datacommons_proto_ErrorCounters_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.datacommons.proto.ErrorCountersOuterClass
            .internal_static_org_datacommons_proto_ErrorCounters_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.class,
                org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.Builder.class);
      }

      // Construct using org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
          getErrorCountersFieldBuilder();
        }
      }

      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (errorCountersBuilder_ == null) {
          errorCounters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          errorCountersBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
        return org.datacommons.proto.ErrorCountersOuterClass
            .internal_static_org_datacommons_proto_ErrorCounters_descriptor;
      }

      @java.lang.Override
      public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters
          getDefaultInstanceForType() {
        return org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.getDefaultInstance();
      }

      @java.lang.Override
      public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters build() {
        org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters buildPartial() {
        org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters result =
            new org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters(this);
        int from_bitField0_ = bitField0_;
        if (errorCountersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            errorCounters_ = java.util.Collections.unmodifiableList(errorCounters_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.errorCounters_ = errorCounters_;
        } else {
          result.errorCounters_ = errorCountersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }

      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.setField(field, value);
      }

      @java.lang.Override
      public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }

      @java.lang.Override
      public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }

      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index,
          java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }

      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field, java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters) {
          return mergeFrom((org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters) other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters other) {
        if (other
            == org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.getDefaultInstance())
          return this;
        if (errorCountersBuilder_ == null) {
          if (!other.errorCounters_.isEmpty()) {
            if (errorCounters_.isEmpty()) {
              errorCounters_ = other.errorCounters_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureErrorCountersIsMutable();
              errorCounters_.addAll(other.errorCounters_);
            }
            onChanged();
          }
        } else {
          if (!other.errorCounters_.isEmpty()) {
            if (errorCountersBuilder_.isEmpty()) {
              errorCountersBuilder_.dispose();
              errorCountersBuilder_ = null;
              errorCounters_ = other.errorCounters_;
              bitField0_ = (bitField0_ & ~0x00000001);
              errorCountersBuilder_ =
                  com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders
                      ? getErrorCountersFieldBuilder()
                      : null;
            } else {
              errorCountersBuilder_.addAllMessages(other.errorCounters_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage =
              (org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters)
                  e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int bitField0_;

      private java.util.List<
              org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter>
          errorCounters_ = java.util.Collections.emptyList();

      private void ensureErrorCountersIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          errorCounters_ =
              new java.util.ArrayList<
                  org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter>(
                  errorCounters_);
          bitField0_ |= 0x00000001;
        }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter,
              org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.Builder,
              org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounterOrBuilder>
          errorCountersBuilder_;

      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public java.util.List<
              org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter>
          getErrorCountersList() {
        if (errorCountersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(errorCounters_);
        } else {
          return errorCountersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public int getErrorCountersCount() {
        if (errorCountersBuilder_ == null) {
          return errorCounters_.size();
        } else {
          return errorCountersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
          getErrorCounters(int index) {
        if (errorCountersBuilder_ == null) {
          return errorCounters_.get(index);
        } else {
          return errorCountersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public Builder setErrorCounters(
          int index,
          org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter value) {
        if (errorCountersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorCountersIsMutable();
          errorCounters_.set(index, value);
          onChanged();
        } else {
          errorCountersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public Builder setErrorCounters(
          int index,
          org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.Builder
              builderForValue) {
        if (errorCountersBuilder_ == null) {
          ensureErrorCountersIsMutable();
          errorCounters_.set(index, builderForValue.build());
          onChanged();
        } else {
          errorCountersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public Builder addErrorCounters(
          org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter value) {
        if (errorCountersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorCountersIsMutable();
          errorCounters_.add(value);
          onChanged();
        } else {
          errorCountersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public Builder addErrorCounters(
          int index,
          org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter value) {
        if (errorCountersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureErrorCountersIsMutable();
          errorCounters_.add(index, value);
          onChanged();
        } else {
          errorCountersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public Builder addErrorCounters(
          org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.Builder
              builderForValue) {
        if (errorCountersBuilder_ == null) {
          ensureErrorCountersIsMutable();
          errorCounters_.add(builderForValue.build());
          onChanged();
        } else {
          errorCountersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public Builder addErrorCounters(
          int index,
          org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.Builder
              builderForValue) {
        if (errorCountersBuilder_ == null) {
          ensureErrorCountersIsMutable();
          errorCounters_.add(index, builderForValue.build());
          onChanged();
        } else {
          errorCountersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public Builder addAllErrorCounters(
          java.lang.Iterable<
                  ? extends
                      org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter>
              values) {
        if (errorCountersBuilder_ == null) {
          ensureErrorCountersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(values, errorCounters_);
          onChanged();
        } else {
          errorCountersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public Builder clearErrorCounters() {
        if (errorCountersBuilder_ == null) {
          errorCounters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          errorCountersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public Builder removeErrorCounters(int index) {
        if (errorCountersBuilder_ == null) {
          ensureErrorCountersIsMutable();
          errorCounters_.remove(index);
          onChanged();
        } else {
          errorCountersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.Builder
          getErrorCountersBuilder(int index) {
        return getErrorCountersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounterOrBuilder
          getErrorCountersOrBuilder(int index) {
        if (errorCountersBuilder_ == null) {
          return errorCounters_.get(index);
        } else {
          return errorCountersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public java.util.List<
              ? extends
                  org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounterOrBuilder>
          getErrorCountersOrBuilderList() {
        if (errorCountersBuilder_ != null) {
          return errorCountersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(errorCounters_);
        }
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.Builder
          addErrorCountersBuilder() {
        return getErrorCountersFieldBuilder()
            .addBuilder(
                org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
                    .getDefaultInstance());
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.Builder
          addErrorCountersBuilder(int index) {
        return getErrorCountersFieldBuilder()
            .addBuilder(
                index,
                org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter
                    .getDefaultInstance());
      }
      /**
       * <code>repeated .org.datacommons.proto.ErrorCounters.ErrorCounter error_counters = 1;</code>
       */
      public java.util.List<
              org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.Builder>
          getErrorCountersBuilderList() {
        return getErrorCountersFieldBuilder().getBuilderList();
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
              org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter,
              org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.Builder,
              org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounterOrBuilder>
          getErrorCountersFieldBuilder() {
        if (errorCountersBuilder_ == null) {
          errorCountersBuilder_ =
              new com.google.protobuf.RepeatedFieldBuilderV3<
                  org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter,
                  org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters.ErrorCounter.Builder,
                  org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters
                      .ErrorCounterOrBuilder>(
                  errorCounters_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          errorCounters_ = null;
        }
        return errorCountersBuilder_;
      }

      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }

      // @@protoc_insertion_point(builder_scope:org.datacommons.proto.ErrorCounters)
    }

    // @@protoc_insertion_point(class_scope:org.datacommons.proto.ErrorCounters)
    private static final org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters
        DEFAULT_INSTANCE;

    static {
      DEFAULT_INSTANCE = new org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters();
    }

    public static org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated
    public static final com.google.protobuf.Parser<ErrorCounters> PARSER =
        new com.google.protobuf.AbstractParser<ErrorCounters>() {
          @java.lang.Override
          public ErrorCounters parsePartialFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws com.google.protobuf.InvalidProtocolBufferException {
            return new ErrorCounters(input, extensionRegistry);
          }
        };

    public static com.google.protobuf.Parser<ErrorCounters> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorCounters> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.datacommons.proto.ErrorCountersOuterClass.ErrorCounters getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }
  }

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_org_datacommons_proto_ErrorCounters_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_datacommons_proto_ErrorCounters_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_org_datacommons_proto_ErrorCounters_ErrorCounter_descriptor;
  private static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_datacommons_proto_ErrorCounters_ErrorCounter_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n\023ErrorCounters.proto\022\025org.datacommons.p"
          + "roto\032\013Debug.proto\"\332\001\n\rErrorCounters\022I\n\016e"
          + "rror_counters\030\001 \003(\01321.org.datacommons.pr"
          + "oto.ErrorCounters.ErrorCounter\032~\n\014ErrorC"
          + "ounter\022\024\n\014counter_name\030\001 \001(\t\022\021\n\tis_prefi"
          + "x\030\002 \001(\010\022/\n\005level\030\003 \001(\0162 .org.datacommons"
          + ".proto.Log.Level\022\024\n\014user_actions\030\004 \003(\t"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              org.datacommons.proto.Debug.getDescriptor(),
            });
    internal_static_org_datacommons_proto_ErrorCounters_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_org_datacommons_proto_ErrorCounters_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_org_datacommons_proto_ErrorCounters_descriptor,
            new java.lang.String[] {
              "ErrorCounters",
            });
    internal_static_org_datacommons_proto_ErrorCounters_ErrorCounter_descriptor =
        internal_static_org_datacommons_proto_ErrorCounters_descriptor.getNestedTypes().get(0);
    internal_static_org_datacommons_proto_ErrorCounters_ErrorCounter_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_org_datacommons_proto_ErrorCounters_ErrorCounter_descriptor,
            new java.lang.String[] {
              "CounterName", "IsPrefix", "Level", "UserActions",
            });
    org.datacommons.proto.Debug.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
