# Production environment substitution variables for Cloud Build.
_ENV_SUFFIX: ''
_PROJECT_ID: 'datcom-import-automation-prod'
_SPANNER_DATABASE_PATH: 'projects/datcom-store/instances/dc-graph-staging/databases/dc_graph_1'
_GCS_BUCKET_ID: 'datcom-prod-imports'
_GCS_MOUNT_BUCKET: 'datcom-volume-mount'
_BQ_DATASET_ID: 'datacommons'
_LOCATION: 'us-central1'
_PROJECT_NUMBER: '965988403328'
_AR_REPO_URL: 'us-docker.pkg.dev/datcom-ci/gcr.io'
_BQ_SPANNER_CONN_ID: 'projects/datcom-import-automation-prod/locations/us/connections/bq_spanner_conn'
_ENABLE_EMBEDDINGS: 'true'
_VERSION: 'stable'
_PROD_TAG: 'stable'
_DATAFLOW_TEMPLATE_PATH: 'gs://datcom-templates/templates/flex/'
