# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  _ENV_SUFFIX: ''

steps:
- id: 'ingestion-helper-service'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'ingestion-helper-service${_ENV_SUFFIX}', '--image', '${_AR_REPO_URL}/datacommons-ingestion-helper:${_VERSION}', '--region', '${_LOCATION}', '--project', '${_PROJECT_ID}', '--no-allow-unauthenticated', '--timeout', '60m', '--set-env-vars', 'PROJECT_ID=${_PROJECT_ID},LOCATION=${_LOCATION},SPANNER_DATABASE_PATH=${_SPANNER_DATABASE_PATH},GCS_BUCKET_ID=${_GCS_BUCKET_ID}']

- id: 'import-helper-service'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'import-helper-service${_ENV_SUFFIX}', '--image', '${_AR_REPO_URL}/datacommons-import-helper:${_VERSION}', '--region', '${_LOCATION}', '--project', '${_PROJECT_ID}', '--no-allow-unauthenticated', '--set-env-vars', 'PROJECT_ID=${_PROJECT_ID},LOCATION=${_LOCATION},PROJECT_NUMBER=${_PROJECT_NUMBER},GCS_BUCKET_ID=${_GCS_BUCKET_ID},INGESTION_HELPER_SERVICE=ingestion-helper-service${_ENV_SUFFIX},SPANNER_INGESTION_WORKFLOW_NAME=spanner-ingestion-workflow${_ENV_SUFFIX},IMPORT_AUTOMATION_WORKFLOW_NAME=import-automation-workflow${_ENV_SUFFIX}']

- id: 'aggregation-helper-job'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'jobs', 'deploy', 'aggregation-helper-job${_ENV_SUFFIX}', '--image', '${_AR_REPO_URL}/datacommons-aggregation-helper:${_VERSION}', '--region', '${_LOCATION}', '--project', '${_PROJECT_ID}', '--tasks', '1', '--max-retries', '0', '--task-timeout', '6h', '--cpu', '4', '--memory', '16Gi', '--set-env-vars', 'PROJECT_ID=${_PROJECT_ID},LOCATION=${_LOCATION},SPANNER_DATABASE_PATH=${_SPANNER_DATABASE_PATH},GCS_BUCKET_ID=${_GCS_BUCKET_ID},BQ_DATASET_ID=${_BQ_DATASET_ID},BQ_SPANNER_CONN_ID=${_BQ_SPANNER_CONN_ID},ENABLE_EMBEDDINGS=${_ENABLE_EMBEDDINGS}']

- id: 'import-automation-workflow'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['workflows', 'deploy', 'import-automation-workflow${_ENV_SUFFIX}', '--project', '${_PROJECT_ID}', '--location', '${_LOCATION}', '--source', 'import-automation-workflow.yaml', '--set-env-vars', 'LOCATION=${_LOCATION},GCS_BUCKET_ID=${_GCS_BUCKET_ID},GCS_MOUNT_BUCKET=${_GCS_MOUNT_BUCKET},PROJECT_NUMBER=${_PROJECT_NUMBER},INGESTION_HELPER_SERVICE=ingestion-helper-service${_ENV_SUFFIX},SPANNER_INGESTION_WORKFLOW_NAME=spanner-ingestion-workflow${_ENV_SUFFIX}']

- id: 'spanner-ingestion-workflow'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['workflows', 'deploy', 'spanner-ingestion-workflow${_ENV_SUFFIX}', '--project', '${_PROJECT_ID}', '--location', '${_LOCATION}', '--source', 'spanner-ingestion-workflow.yaml', '--set-env-vars', 'LOCATION=${_LOCATION},PROJECT_ID=${_PROJECT_ID},SPANNER_DATABASE_PATH=${_SPANNER_DATABASE_PATH},PROJECT_NUMBER=${_PROJECT_NUMBER},DATAFLOW_TEMPLATE_PATH=${_DATAFLOW_TEMPLATE_PATH}ingestion-${_VERSION}.json,INGESTION_HELPER_SERVICE=ingestion-helper-service${_ENV_SUFFIX},AGGREGATION_JOB_NAME=aggregation-helper-job${_ENV_SUFFIX}']

options:
  logging: CLOUD_LOGGING_ONLY
